name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # Paso 1: Tomar todo el codigo del repo
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    # paso 2: logearse en docker
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.TOKEN_PASSWORD }}
      run: |
        echo "Inicio Docker Login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Fin Docker login"

    # 3. build docker image
    - name: Build docker image
      run: | 
        docker build -t gregory213/graphql-actions:0.0.2 .
        docker build -t gregory213/graphql-actions .

    # 4. push docker image
    - name: Push docker image
      run: |
        docker image push gregory213/graphql-actions:0.0.2
        docker image push gregory213/graphql-actions
    # - name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
